import { type NextPage } from 'next';
import Head from 'next/head';
import Header from '~/components/Header/Header';
import Timer from '~/components/Timer/Timer';
import Footer from '~/components/Footer';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex h-screen items-center justify-center">
                <div className="h-full w-full max-w-md md:h-[90%] md:rounded-xl md:shadow-md md:dark:bg-slate-800/10 md:dark:shadow-lg">
                    <Header />
                    <Timer />
                    <Footer />
                </div>
            </div>
        </>
    );
};

export default Home;
