import { type NextPage } from 'next';
import Head from 'next/head';
import Header from '~/components/Header/Header';
import Timer from '~/components/Timer/Timer';
import Footer from '~/components/Footer';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Gaps Learning Timer</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex h-screen justify-center">
                <div className="h-full w-full dark:shadow-lg md:max-w-lg">
                    <Header />
                    <Timer />
                    <Footer />
                </div>
            </div>
        </>
    );
};

export default Home;
